/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ldshr.h"

bool_t
xdr_load_result (XDR *xdrs, load_result *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->load_avg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_params (XDR *xdrs, max_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->N))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->M))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->S))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_result (XDR *xdrs, max_result *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->max_value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_node (XDR *xdrs, node *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (node), (xdrproc_t) xdr_node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_result (XDR *xdrs, list_result *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->head, sizeof (node), (xdrproc_t) xdr_node))
		 return FALSE;
	return TRUE;
}
