/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ldshr.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

load_result *
getload_1(void *argp, CLIENT *clnt)
{
	static load_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETLOAD,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_load_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

max_result *
getmax_gpu_1(max_params *argp, CLIENT *clnt)
{
	static max_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETMAX_GPU,
		(xdrproc_t) xdr_max_params, (caddr_t) argp,
		(xdrproc_t) xdr_max_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

list_result *
upd_lst_1(list_result *argp, CLIENT *clnt)
{
	static list_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPD_LST,
		(xdrproc_t) xdr_list_result, (caddr_t) argp,
		(xdrproc_t) xdr_list_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
