/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LDSHR_H_RPCGEN
#define _LDSHR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct load_result {
	double load_avg;
};
typedef struct load_result load_result;

struct max_params {
	int N;
	double M;
	int S;
};
typedef struct max_params max_params;

struct max_result {
	double max_value;
};
typedef struct max_result max_result;

struct node {
	double value;
	struct node *next;
};
typedef struct node node;

struct list_result {
	node *head;
};
typedef struct list_result list_result;

#define LOADSHR_PROG 0x20000001
#define LOADSHR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETLOAD 1
extern  load_result * getload_1(void *, CLIENT *);
extern  load_result * getload_1_svc(void *, struct svc_req *);
#define GETMAX_GPU 2
extern  max_result * getmax_gpu_1(max_params *, CLIENT *);
extern  max_result * getmax_gpu_1_svc(max_params *, struct svc_req *);
#define UPD_LST 3
extern  list_result * upd_lst_1(list_result *, CLIENT *);
extern  list_result * upd_lst_1_svc(list_result *, struct svc_req *);
extern int loadshr_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETLOAD 1
extern  load_result * getload_1();
extern  load_result * getload_1_svc();
#define GETMAX_GPU 2
extern  max_result * getmax_gpu_1();
extern  max_result * getmax_gpu_1_svc();
#define UPD_LST 3
extern  list_result * upd_lst_1();
extern  list_result * upd_lst_1_svc();
extern int loadshr_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_load_result (XDR *, load_result*);
extern  bool_t xdr_max_params (XDR *, max_params*);
extern  bool_t xdr_max_result (XDR *, max_result*);
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_list_result (XDR *, list_result*);

#else /* K&R C */
extern bool_t xdr_load_result ();
extern bool_t xdr_max_params ();
extern bool_t xdr_max_result ();
extern bool_t xdr_node ();
extern bool_t xdr_list_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LDSHR_H_RPCGEN */
